# Generated by Django 3.2.5 on 2023-10-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentBulkUpload',
        ),
    ]
